services:
  postgres:
    image: postgres:17.5-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_spring_ecommerce
    ports:
      - "5432:5432"